CREATE TABLE ams.`attendance` (
  `id` bigint(20) NOT NULL,
  `training_id` bigint(20) DEFAULT NULL,
  `student_id` bigint(20) DEFAULT NULL,
  `attended` tinyint(4) DEFAULT NULL,
  `reason` longtext,
  `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_by` bigint(25) DEFAULT NULL,
  `review_status` bigint(20) DEFAULT NULL,
  `reviewed_by` bigint(20) DEFAULT NULL,
  `review_comments` blob,
  PRIMARY KEY (`id`),
  KEY `training_fk` (`training_id`),
  KEY `student_fk` (`student_id`),
  KEY `modified_by` (`modified_by`),
  KEY `review_status` (`review_status`),
  KEY `approved_by` (`reviewed_by`),
  CONSTRAINT `attendance_ibfk_1` FOREIGN KEY (`modified_by`) REFERENCES `users` (`id`),
  CONSTRAINT `attendance_ibfk_2` FOREIGN KEY (`review_status`) REFERENCES `seed_status` (`id`),
  CONSTRAINT `attendance_ibfk_3` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`),
  CONSTRAINT `student_fk` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `training_fk` FOREIGN KEY (`training_id`) REFERENCES `training` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
